
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLOR KIND MATERIAL NUMBER OPERATE SIZEcommand : OPERATE NUMBER articlecommand : OPERATEcommand : OPERATE OPERATE articleattribute : COLORattribute : MATERIALattribute : SIZEarticle : KINDarticle : attribute article'
    
_lr_action_items = {'OPERATE':([0,2,],[2,3,]),'$end':([1,2,5,6,11,12,],[0,-2,-3,-7,-1,-8,]),'NUMBER':([2,],[4,]),'KIND':([3,4,7,8,9,10,],[6,6,6,-4,-5,-6,]),'COLOR':([3,4,7,8,9,10,],[8,8,8,-4,-5,-6,]),'MATERIAL':([3,4,7,8,9,10,],[9,9,9,-4,-5,-6,]),'SIZE':([3,4,7,8,9,10,],[10,10,10,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'article':([3,4,7,],[5,11,12,]),'attribute':([3,4,7,],[7,7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> OPERATE NUMBER article','command',3,'p_command','main.py',94),
  ('command -> OPERATE','command',1,'p_show_command','main.py',116),
  ('command -> OPERATE OPERATE article','command',3,'p_how_many_command','main.py',123),
  ('attribute -> COLOR','attribute',1,'p_attribute_color','main.py',130),
  ('attribute -> MATERIAL','attribute',1,'p_attribute_material','main.py',135),
  ('attribute -> SIZE','attribute',1,'p_attribute_size','main.py',140),
  ('article -> KIND','article',1,'p_article_kind','main.py',145),
  ('article -> attribute article','article',2,'p_article_attribute','main.py',150),
]
